#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nose-cov
Version  : 1.6
Release  : 5
URL      : https://pypi.python.org/packages/source/n/nose-cov/nose-cov-1.6.tar.gz
Source0  : https://pypi.python.org/packages/source/n/nose-cov/nose-cov-1.6.tar.gz
Summary  : nose plugin for coverage reporting, including subprocesses and multiprocessing
Group    : Development/Tools
License  : MIT
Requires: nose-cov-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
nose-cov
========
This plugin produces coverage reports.  It also supports coverage of subprocesses.

%package python
Summary: python components for the nose-cov package.
Group: Default

%description python
python components for the nose-cov package.


%prep
%setup -q -n nose-cov-1.6

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
